title: Home of Zixuan
author: yaozixuan
email: yao@jhu.edu
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage
# baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /:title/
texture:
  title: Zixuan (Vincent) Yao
  tagline: Student ==> Software Engineer
  date_format: "%b %-d, %Y"
  style: blue
  showNav: true
  showPicker: false

  navigation:
    - title: Home
      url: "/"
    - title: Resume
      url: "/resume"
    - title: Projects
      url: "/projects"

  # generate social links in footer
  social_links:
    # twitter: thelehhman
    github:  yaozixuan
    linkedIn: in/yaozixuan
    email: yao@jhu.edu
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture
remote_theme: thelehhman/texture

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
#  - jekyll-feed

repository: yaozixuan/project